# Generated by Django 6.0.7 on 2026-07-30 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesRecord',
            new_name='SaleRecord',
        ),
    ]
